[build]
  command = "npm install --platform=linux --arch=x64 @rollup/rollup-linux-x64-gnu && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle SPA routing (for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers with more permissive CSP
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Very permissive CSP to allow all resources and fix wallet icon issues
    Content-Security-Policy = "default-src * 'self' data: blob: 'unsafe-inline' 'unsafe-eval'; connect-src * 'self' ws: wss:; img-src * 'self' data: blob:; frame-src * 'self'; worker-src * 'self' blob:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 