[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing (for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers with more permissive CSP
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # More permissive CSP for blockchain apps
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.infura.io wss://*.infura.io https://*.alchemyapi.io wss://*.alchemyapi.io https://*.etherscan.io https://ethereum.publicnode.com wss://*.bridge.walletconnect.org https://*.supabase.co https://api.gemini.google.com https://sepolia.infura.io wss://sepolia.infura.io ws://localhost:* https://api.blocknative.com; img-src 'self' data: https://raw.githubusercontent.com https://*.walletconnect.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; frame-src 'self' https://verify.walletconnect.org https://*.walletconnect.com; worker-src 'self' blob:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 